### ISSUE TITLE
libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation whenusing with pypro

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/curl-feedstock#138]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We found an undefined symbol problem in py310 and py311

```
Client 127.0.0.1:37096] request declined in mgs_hook_fixups
mod_wsgi (pid=13166, process='DEMO', application=''): Loading Python script file '/home/user/DEMO/wsgi/wms.wsgi'.
mod_wsgi (pid=13166): Failed to exec Python script file '/DEMO/wsgi/wms.wsgi'.
mod_wsgi (pid=13166): Exception occurred processing WSGI script 'wms.wsgi'.
Traceback (most recent call last):
  File "/DEMO/wsgi/wms.wsgi", line 29, in <module>
    from mslib.mswms.wms import app as application
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/wms.py", line 67, in <module>
    from mslib.mswms.gallery_builder import add_image, write_html, add_levels, add_times, \\
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/gallery_builder.py", line 35, in <module>
    from mslib.mswms.mpl_vsec import AbstractVerticalSectionStyle
  File "mssenv/lib/python3.10/site-packages/mslib/mswms/mpl_vsec.py", line 42, in <module>
    from mslib.utils.units import convert_to, units
  File "mssenv/lib/python3.10/site-packages/mslib/utils/units.py", line 31, in <module>
    from metpy.units import units, check_units  # noqa
  File "mssenv/lib/python3.10/site-packages/metpy/__init__.py", line 15, in <module>
    from .xarray import *  # noqa: F401, F403, E402
  File "mssenv/lib/python3.10/site-packages/metpy/xarray.py", line 26, in <module>
    from pyproj import CRS, Proj
  File "mssenv/lib/python3.10/site-packages/pyproj/__init__.py", line 33, in <module>
    import pyproj.network
  File "mssenv/lib/python3.10/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: mssenv/lib/python3.10/site-packages/pyproj/../../.././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
AH02001: Connection closed to child 512 with standard shutdown (server
```)
```

```
mod_wsgi (pid=5246): Failed to exec Python script file '/home/user/DEMO/wsgi/wms.wsgi'.
[Thu May 23mod_wsgi (pid=5246): Exception occurred processing WSGI script '/home/user/DEMO/wsgi/wms.wsgi'.
Traceback (most recent call last):
 File "/home/user/DEMO/wsgi/wms.wsgi", line 16, in <module>
   from mslib.mswms.wms import app as application
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mslib/mswms/wms.py", line 67, in <module>
   from mslib.mswms.gallery_builder import add_image, write_html, add_levels, add_times, \\
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mslib/mswms/gallery_builder.py", line 35, in <module>
   from mslib.mswms.mpl_vsec import AbstractVerticalSectionStyle
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mslib/mswms/mpl_vsec.py", line 42, in <module>
   from mslib.utils.units import convert_to, units
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mslib/utils/units.py", line 31, in <module>
   from metpy.units import units, check_units  # noqa
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/metpy/__init__.py", line 15, in <module>
   from .xarray import *  # noqa: F401, F403, E402
   ^^^^^^^^^^^^^^^^^^^^^
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/metpy/xarray.py", line 26, in <module>
   from pyproj import CRS, Proj
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/pyproj/__init__.py", line 33, in <module>
   import pyproj.network
 File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/pyproj/network.py", line 10, in <module>
   from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
[Thu May 23 ImportError: /home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/pyproj/../../.././libcurl.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
```
linking to https://github.com/Open-MSS/MSS/issues/2387

The last version without this was 7.87.0

### Installed packages

```shell
### Installed packages


# packages in environment at /home/user/Miniforge/envs/mssenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alembic                   1.13.1             pyhd8ed1ab_1    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311h459d7ec_4    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.tarfile         1.0.0              pyhd8ed1ab_1    conda-forge
basemap                   1.4.1           np126py311hb1fe3e7_0    conda-forge
basemap-data              1.3.2              pyhd8ed1ab_3    conda-forge
bcrypt                    4.1.3           py311h5ecf98a_0    conda-forge
bidict                    0.23.1             pyhd8ed1ab_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cachetools                5.3.3              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
cartopy                   0.23.0          py311h14de704_1    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
cftime                    1.6.3           py311h18e1886_1    conda-forge
chameleon                 3.9.1              pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
contourpy                 1.2.1           py311h9547e67_0    conda-forge
cryptography              42.0.2          py311hcb13ee4_0    conda-forge
curl                      8.1.2                h409715c_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
dbus-python               1.3.2           py311h703f8ee_4    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dnspython                 2.6.1              pyhd8ed1ab_1    conda-forge
elementpath               4.4.0              pyhd8ed1ab_0    conda-forge
email-validator           2.1.1              pyhd8ed1ab_0    conda-forge
email_validator           2.1.1                hd8ed1ab_0    conda-forge
execnet                   2.1.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
fastkml                   0.12               pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
flask                     2.3.3              pyhd8ed1ab_0    conda-forge
flask-cors                4.0.0              pyhd8ed1ab_0    conda-forge
flask-httpauth            4.8.0              pyhd8ed1ab_0    conda-forge
flask-login               0.6.3              pyhd8ed1ab_1    conda-forge
flask-mail                0.9.1                      py_2    conda-forge
flask-migrate             4.0.7              pyhd8ed1ab_0    conda-forge
flask-socketio            5.3.6              pyhd8ed1ab_0    conda-forge
flask-sqlalchemy          3.0.3              pyhd8ed1ab_0    conda-forge
flask-wtf                 1.2.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.51.0          py311h459d7ec_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fs                        2.4.16             pyhd8ed1ab_0    conda-forge
fs.sshfs                  1.0.2              pyhd8ed1ab_0    conda-forge
fs.webdavfs               0.4.2              pyhd8ed1ab_0    conda-forge
fs_filepicker             0.3.7              pyhd8ed1ab_5    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
geos                      3.12.1               h59595ed_0    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
git                       2.42.0          pl5321h86e50cf_0    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
glib                      2.78.1               hfc55251_0    conda-forge
glib-tools                2.78.1               hfc55251_0    conda-forge
gpxpy                     1.6.2              pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
greenlet                  3.0.3           py311hb755f60_0    conda-forge
gst-plugins-base          1.22.0               h4243ec0_2    conda-forge
gstreamer                 1.22.0               h25f0c4b_2    conda-forge
gstreamer-orc             0.4.38               hd590300_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h4df4325_101    conda-forge
humanfriendly             10.0               pyhd8ed1ab_6    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jack                      1.9.22               h11f4161_0    conda-forge
jaraco.classes            3.4.0              pyhd8ed1ab_1    conda-forge
jaraco.context            5.3.0              pyhd8ed1ab_1    conda-forge
jaraco.functools          4.0.0              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
jplephem                  2.21               pyh864a33b_0    conda-forge
keyring                   25.2.1             pyha804496_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py311h9547e67_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.67                 he9d0100_0    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libclang                  15.0.7          default_h127d8a8_5    conda-forge
libclang13                15.0.7          default_h5d6823c_5    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgcrypt                 1.10.3               hd590300_0    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libglib                   2.78.1               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libgpg-error              1.49                 h4f305b6_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm15                 15.0.7               hadd5161_1    conda-forge
libnetcdf                 4.9.1           nompi_h34a3ff0_101    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     15.3                 hbcd7760_1    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libsystemd0               253                  h8c4010b_1    conda-forge
libtiff                   4.4.0                h82bc61c_5    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libudev1                  253                  h0b41bf4_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.4                h522a892_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.5.0                h79f4944_1    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libxmlsec1                1.2.37               h927ea9a_0    conda-forge
libxslt                   1.1.37               h873f0b0_0    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lxml                      4.9.2           py311h14a6109_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
mako                      1.3.5              pyhd8ed1ab_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
matplotlib                3.8.4           py311h38be061_2    conda-forge
matplotlib-base           3.8.4           py311ha4ca890_2    conda-forge
metpy                     1.6.2              pyhd8ed1ab_0    conda-forge
mod_wsgi                  5.0.0           py311h459d7ec_0    conda-forge
more-itertools            10.2.0             pyhd8ed1ab_0    conda-forge
mpg123                    1.32.6               h59595ed_0    conda-forge
mss                       9.0.0           py311h38be061_0    conda-forge
multidict                 6.0.5           py311h459d7ec_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.33               hf1915f5_6    conda-forge
mysql-libs                8.0.33               hca2cd23_6    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
netcdf4                   1.6.3           nompi_py311ha396515_100    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.100                hca3bf56_0    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   3.1.5                h4ab18f5_1    conda-forge
owslib                    0.31.0             pyhd8ed1ab_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311h14de704_1    conda-forge
paramiko                  3.4.0              pyhd8ed1ab_0    conda-forge
passlib                   1.7.4              pyhd8ed1ab_1    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    9.2.0           py311h9461556_3    conda-forge
pint                      0.23               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pooch                     1.8.1              pyhd8ed1ab_0    conda-forge
proj                      9.1.1                h93bde94_0    conda-forge
property-cached           1.6.4                      py_0    conda-forge
psycopg2                  2.9.6           py311h68d4568_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio                16.1                 hcb278e6_3    conda-forge
pulseaudio-client         16.1                 h5195f5e_3    conda-forge
pulseaudio-daemon         16.1                 ha8d29e2_3    conda-forge
pycountry                 22.3.5             pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygeoif                   0.7                        py_1    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    conda-forge
pymysql                   1.1.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py311h459d7ec_3    conda-forge
pyopenssl                 24.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyproj                    3.5.0           py311h945b3ca_0    conda-forge
pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_5    conda-forge
pysaml2                   7.5.0              pyhd8ed1ab_0    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-engineio           4.9.1              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.4              pyhd8ed1ab_0    conda-forge
python-socketio           5.11.2             pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
qt                        5.15.8               hf11cfaa_0    conda-forge
qt-main                   5.15.8               h5d23da1_6    conda-forge
qt-webengine              5.15.8               h77d6d84_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.2             pyhd8ed1ab_0    conda-forge
scipy                     1.13.0          py311h517d4fd_1    conda-forge
secretstorage             3.3.3           py311h38be061_2    conda-forge
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
sgp4                      2.22            py311h92ebd52_0    conda-forge
shapely                   2.0.4           py311h0bed3d6_1    conda-forge
simple-websocket          1.0.0              pyhd8ed1ab_1    conda-forge
sip                       6.7.12          py311hb755f60_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
skyfield                  1.48               pyhca7485f_0    conda-forge
skyfield-data             5.0.0              pyhd8ed1ab_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.30          py311h331c9d8_0    conda-forge
sqlite                    3.45.3               h2c6b66d_0    conda-forge
text-unidecode            1.3                pyhd8ed1ab_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4             py311h459d7ec_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
validate_email            1.3                        py_3    conda-forge
webdavclient3             3.14.5             pyhd8ed1ab_1    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
werkzeug                  2.3.8              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wsproto                   1.2.0              pyhd8ed1ab_0    conda-forge
wtforms                   3.1.2              pyhd8ed1ab_0    conda-forge
xarray                    2024.5.0           pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                h516909a_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h516909a_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h516909a_0    conda-forge
xkeyboard-config          2.38                 h0b41bf4_0    conda-forge
xmlschema                 2.5.1              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xstatic                   1.0.2              pyh9f0ad1d_0    conda-forge
xstatic-bootstrap         4.5.3.1            pyhd3deb0d_0    conda-forge
xstatic-jquery            3.5.1.1            pyhd8ed1ab_5    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
### Environment info


mamba version : 1.5.8
     active environment : mssenv
    active env location : /home/user/Miniforge/envs/mssenv
            shell level : 2
       user config file : /home/user/.condarc
 populated config files : /home/user/Miniforge/.condarc
                          /home/user/.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.3.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/user/Miniforge  (writable)
      conda av data dir : /home/user/Miniforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/user/Miniforge/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/Miniforge/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Linux/5.15.0-107-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 2000:33
             netrc file : None
           offline mode : False
```

**Comment by ReimarBauer** [comment]
This changed to 

`ImportError: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/mss-ascci/miniforge3/envs/mssenv/lib/python3.10/site-packages/pyproj/../../.././libcurl.so.4)`

for ibcurl                   8.10.1               hbbe4b11_0

**Comment by mkf62** [comment]
Experiencing the same issue.
